### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JL2210** [accountantM/CurlMultiTimeoutBugTester#1]
https://github.com/accountantM/CurlMultiTimeoutBugTester/blob/613e473e2381c128903f73318e19b65e5af18b64/C%20programs/curl-multi-tester/main.c#L70

It's supposed to be spelled "summary".

**Comment by accountantM** [comment]
Thank you very much, I updated them in both programs and in the [cron job line in readme file](https://github.com/accountantM/CurlMultiTimeoutBugTester/blob/master/C%20programs/README.md)
